steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/kubernetes-assignment-428501/k8-artifactregistry-container2/k8-container2:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/kubernetes-assignment-428501/k8-artifactregistry-container2/k8-container2:latest",
      ]

options:
  logging: NONE

serviceAccount: "k8-assignment-serviceaccount@kubernetes-assignment-428501.iam.gserviceaccount.com"
