apiVersion: v1
kind: PersistentVolume
metadata:
  name: poojitha-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /poojitha_PV_dir
