apiVersion: v1
kind: Service
metadata:
  name: poojitha-service-2
  labels:
    app: poojitha-app
spec:
  selector:
    app: poojitha-app
  ports:
    - name: container-2
      protocol: TCP
      port: 80
      targetPort: 4000
